### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by rtm7777** [sashasashas11/expertise-nodejs#1]
Залий шолі кудись, позирить )

**Comment by vitalyp** [comment]
Стяни собi i подивись ))

**Comment by rtm7777** [comment]
та ну, а тоді ше всі завісімості і остальне, чо б не виложить на  хероку чи опеншіфт

**Comment by vitalyp** [comment]
Саша, приубавь системные требования своей проги. Ею же никто не сможет пользоваться!
